/**
 * Week 2 Interview-Aligned Curriculum Data
 * 20 activities + 20 quiz questions per topic; activities and quizzes align on interview concepts.
 * Used by seedCurriculum.js to populate each topic.
 */

// Topic 1: How Java is Compiled — 20 activities, 20 quiz (interview-aligned)
const compilationActivities = [
  { type: 'drag-order', instruction: 'Interview: Order the Java compilation and execution pipeline.', options: [{ id: 'lex', text: 'Lexical analysis (tokens)', correctOrder: 1 }, { id: 'syn', text: 'Syntax analysis (AST)', correctOrder: 2 }, { id: 'sem', text: 'Semantic analysis (types, scope)', correctOrder: 3 }, { id: 'byte', text: 'Bytecode generation', correctOrder: 4 }, { id: 'load', text: 'Class loading (JVM)', correctOrder: 5 }], correctAnswer: ['lex', 'syn', 'sem', 'byte', 'load'], explanation: 'Compiler: lexical → syntax → semantic → bytecode. Then JVM loads the class.' },
  { type: 'multiple-choice', instruction: 'Interview: Why does Java use bytecode instead of compiling to machine code?', options: [{ id: 'a', text: 'Bytecode runs faster' }, { id: 'b', text: 'Bytecode is platform-independent; same .class runs on any JVM' }, { id: 'c', text: 'Machine code is not allowed' }, { id: 'd', text: 'Bytecode is smaller' }], correctAnswer: 'b', explanation: 'Write once, run anywhere: JVM per platform interprets/JIT-compiles bytecode.' },
  { type: 'multiple-choice', instruction: 'Interview: What does lexical analysis produce?', options: [{ id: 'a', text: 'AST' }, { id: 'b', text: 'Tokens (keywords, identifiers, operators, literals)' }, { id: 'c', text: 'Bytecode' }, { id: 'd', text: 'Machine code' }], correctAnswer: 'b', explanation: 'Lexical analysis tokenizes source code.' },
  { type: 'match-pairs', instruction: 'Interview: Match JVM class-loading phase to its role.', options: [{ id: 'load', text: 'Loading', correctMatch: 'l1' }, { id: 'link', text: 'Linking', correctMatch: 'l2' }, { id: 'init', text: 'Initialization', correctMatch: 'l3' }], matchOptions: [{ id: 'l1', text: 'Reads .class file; creates Class object' }, { id: 'l2', text: 'Verification, preparation, resolution' }, { id: 'l3', text: 'Runs static initializers; sets static fields' }], correctAnswer: [['load', 'l1'], ['link', 'l2'], ['init', 'l3']], explanation: 'Loading reads .class; Linking verifies/prepares/resolves; Initialization runs statics.' },
  { type: 'multiple-choice', instruction: 'Interview: What is JIT?', options: [{ id: 'a', text: 'A Java IDE' }, { id: 'b', text: 'Just-In-Time compilation: JVM compiles hot bytecode to native code' }, { id: 'c', text: 'A bytecode format' }, { id: 'd', text: 'A garbage collector' }], correctAnswer: 'b', explanation: 'JIT compiles frequently executed bytecode to native machine code for speed.' },
  { type: 'drag-order', instruction: 'Order JVM class-loading phases.', options: [{ id: 'ld', text: 'Loading', correctOrder: 1 }, { id: 'ln', text: 'Linking', correctOrder: 2 }, { id: 'in', text: 'Initialization', correctOrder: 3 }], correctAnswer: ['ld', 'ln', 'in'], explanation: 'Loading → Linking → Initialization.' },
  { type: 'multiple-choice', instruction: 'Interview: What is the AST?', options: [{ id: 'a', text: 'A token' }, { id: 'b', text: 'Abstract Syntax Tree; parser builds it from tokens' }, { id: 'c', text: 'A bytecode instruction' }, { id: 'd', text: 'A JVM heap area' }], correctAnswer: 'b', explanation: 'AST represents grammatical structure; built during syntax analysis.' },
  { type: 'match-pairs', instruction: 'Match tool/artifact to its role.', options: [{ id: 'javac', text: 'javac', correctMatch: 'c' }, { id: 'jvm', text: 'JVM', correctMatch: 'r' }, { id: 'byte', text: 'bytecode', correctMatch: 'p' }], matchOptions: [{ id: 'c', text: 'Compiles .java to .class' }, { id: 'r', text: 'Runs .class (interpret/JIT)' }, { id: 'p', text: 'Platform-independent instructions' }], correctAnswer: [['javac', 'c'], ['jvm', 'r'], ['byte', 'p']], explanation: 'javac compiles; JVM runs; bytecode is the portable format.' },
  { type: 'multiple-choice', instruction: 'Interview: When is bytecode verified?', options: [{ id: 'a', text: 'At compile time by javac' }, { id: 'b', text: 'During JVM Linking phase' }, { id: 'c', text: 'Never' }, { id: 'd', text: 'Only in debug mode' }], correctAnswer: 'b', explanation: 'Verification happens in the Linking phase of class loading.' },
  { type: 'multiple-choice', instruction: 'Interview: What does semantic analysis do?', options: [{ id: 'a', text: 'Tokenizes source' }, { id: 'b', text: 'Type checking, scope, method signatures' }, { id: 'c', text: 'Generates bytecode' }, { id: 'd', text: 'Loads the class' }], correctAnswer: 'b', explanation: 'Semantic analysis validates types, scope, and method signatures.' },
  { type: 'drag-order', instruction: 'From source to execution: order the steps.', options: [{ id: 'src', text: 'Source code (.java)', correctOrder: 1 }, { id: 'comp', text: 'Compilation (javac)', correctOrder: 2 }, { id: 'bc', text: 'Bytecode (.class)', correctOrder: 3 }, { id: 'load', text: 'Load + Execute (JVM)', correctOrder: 4 }], correctAnswer: ['src', 'comp', 'bc', 'load'], explanation: 'Source → compile → bytecode → JVM loads and runs.' },
  { type: 'multiple-choice', instruction: 'Interview: Can the same .class file run on Windows and Linux?', options: [{ id: 'a', text: 'No' }, { id: 'b', text: 'Yes; bytecode is platform-independent' }, { id: 'c', text: 'Only if recompiled' }, { id: 'd', text: 'Only with special flags' }], correctAnswer: 'b', explanation: 'Same bytecode runs on any platform with a JVM.' },
  { type: 'match-pairs', instruction: 'Match phase to output.', options: [{ id: 'lex', text: 'Lexical', correctMatch: 'tok' }, { id: 'syn', text: 'Syntax', correctMatch: 'ast' }, { id: 'sem', text: 'Semantic', correctMatch: 'typ' }, { id: 'gen', text: 'Bytecode gen', correctMatch: 'cls' }], matchOptions: [{ id: 'tok', text: 'Tokens' }, { id: 'ast', text: 'AST' }, { id: 'typ', text: 'Type/scope validation' }, { id: 'cls', text: '.class file' }], correctAnswer: [['lex', 'tok'], ['syn', 'ast'], ['sem', 'typ'], ['gen', 'cls']], explanation: 'Lexical→tokens; Syntax→AST; Semantic→validation; Bytecode gen→.class.' },
  { type: 'multiple-choice', instruction: 'Interview: Why not compile directly to machine code?', options: [{ id: 'a', text: 'Machine code is illegal' }, { id: 'b', text: 'Portability; one bytecode runs everywhere' }, { id: 'c', text: 'Bytecode is faster' }, { id: 'd', text: 'Security only' }], correctAnswer: 'b', explanation: 'Direct machine code would be platform-specific; bytecode gives portability.' },
  { type: 'multiple-choice', instruction: 'Interview: Who performs JIT compilation?', options: [{ id: 'a', text: 'javac' }, { id: 'b', text: 'JVM at runtime' }, { id: 'c', text: 'The OS' }, { id: 'd', text: 'The linker' }], correctAnswer: 'b', explanation: 'The JVM JIT-compiles hot bytecode to native code at runtime.' },
  { type: 'drag-order', instruction: 'Order compiler phases.', options: [{ id: 'l', text: 'Lexical analysis', correctOrder: 1 }, { id: 's', text: 'Syntax analysis', correctOrder: 2 }, { id: 'e', text: 'Semantic analysis', correctOrder: 3 }, { id: 'g', text: 'Bytecode generation', correctOrder: 4 }], correctAnswer: ['l', 's', 'e', 'g'], explanation: 'Lexical → Syntax → Semantic → Bytecode.' },
  { type: 'multiple-choice', instruction: 'Interview: What happens in the Initialization phase?', options: [{ id: 'a', text: 'Reading .class file' }, { id: 'b', text: 'Running static initializers and setting static fields' }, { id: 'c', text: 'Verification only' }, { id: 'd', text: 'JIT compilation' }], correctAnswer: 'b', explanation: 'Initialization executes static blocks and assigns static field values.' },
  { type: 'match-pairs', instruction: 'Match term to meaning.', options: [{ id: 'ast', text: 'AST', correctMatch: 'tree' }, { id: 'jit', text: 'JIT', correctMatch: 'runtime' }, { id: 'jvm', text: 'JVM', correctMatch: 'run' }], matchOptions: [{ id: 'tree', text: 'Abstract Syntax Tree' }, { id: 'runtime', text: 'Just-In-Time compilation' }, { id: 'run', text: 'Java Virtual Machine' }], correctAnswer: [['ast', 'tree'], ['jit', 'runtime'], ['jvm', 'run']], explanation: 'AST = tree; JIT = runtime compilation; JVM = runtime.' },
  { type: 'multiple-choice', instruction: 'Interview: What runs first on bytecode?', options: [{ id: 'a', text: 'JIT only' }, { id: 'b', text: 'Interpreter; JIT may compile hot code later' }, { id: 'c', text: 'Native code only' }, { id: 'd', text: 'Compiler' }], correctAnswer: 'b', explanation: 'JVM typically interprets first; JIT compiles hot paths to native code.' },
  { type: 'multiple-choice', instruction: 'Interview: What is in the constant pool of a .class file?', options: [{ id: 'a', text: 'Only numbers' }, { id: 'b', text: 'Literals, symbolic references, metadata' }, { id: 'c', text: 'Source code' }, { id: 'd', text: 'Native code' }], correctAnswer: 'b', explanation: 'Constant pool holds literals and references used by bytecode.' },
];

const compilationQuizzes = [
  { question: 'Interview: What does the Java compiler produce?', options: [{ id: 'a', text: 'Native machine code' }, { id: 'b', text: 'Bytecode (.class)' }, { id: 'c', text: 'Assembly' }, { id: 'd', text: 'Source' }], correctOptionId: 'b', explanation: 'Compiler produces bytecode; JVM interprets/JIT-compiles it.' },
  { question: 'Interview: Which phase checks variable types and method signatures?', options: [{ id: 'a', text: 'Lexical' }, { id: 'b', text: 'Syntax' }, { id: 'c', text: 'Semantic' }, { id: 'd', text: 'Bytecode gen' }], correctOptionId: 'c', explanation: 'Semantic analysis does type and scope checking.' },
  { question: 'Interview: Difference between compilation and interpretation in Java?', options: [{ id: 'a', text: 'Java only interpreted' }, { id: 'b', text: 'javac compiles to bytecode; JVM interprets and JIT-compiles' }, { id: 'c', text: 'Java only compiled' }, { id: 'd', text: 'Interpret before compile' }], correctOptionId: 'b', explanation: 'javac → bytecode; JVM interprets and JIT-compiles hot code.' },
  { question: 'Interview: Which JVM phase runs static initializers?', options: [{ id: 'a', text: 'Loading' }, { id: 'b', text: 'Linking' }, { id: 'c', text: 'Initialization' }, { id: 'd', text: 'Verification' }], correctOptionId: 'c', explanation: 'Initialization runs static blocks and sets static fields.' },
  { question: 'Interview: What is lexical analysis?', options: [{ id: 'a', text: 'Type checking' }, { id: 'b', text: 'Breaking source into tokens' }, { id: 'c', text: 'Building AST' }, { id: 'd', text: 'Generating bytecode' }], correctOptionId: 'b', explanation: 'Lexical analysis tokenizes the source code.' },
  { question: 'Interview: What is the AST used for?', options: [{ id: 'a', text: 'Storage' }, { id: 'b', text: 'Representing grammatical structure for syntax/semantic analysis' }, { id: 'c', text: 'Execution' }, { id: 'd', text: 'Networking' }], correctOptionId: 'b', explanation: 'AST represents program structure for the compiler.' },
  { question: 'Interview: When is bytecode verified?', options: [{ id: 'a', text: 'By javac' }, { id: 'b', text: 'During JVM Linking' }, { id: 'c', text: 'Never' }, { id: 'd', text: 'At load only' }], correctOptionId: 'b', explanation: 'Verification is part of the Linking phase.' },
  { question: 'Interview: What is JIT?', options: [{ id: 'a', text: 'A compiler' }, { id: 'b', text: 'Just-In-Time compilation of bytecode to native code by JVM' }, { id: 'c', text: 'A GC' }, { id: 'd', text: 'A tool' }], correctOptionId: 'b', explanation: 'JIT compiles hot bytecode to native code at runtime.' },
  { question: 'Interview: Can one .class run on different OS?', options: [{ id: 'a', text: 'No' }, { id: 'b', text: 'Yes; bytecode is platform-independent' }, { id: 'c', text: 'Only Windows' }, { id: 'd', text: 'Only with recompile' }], correctOptionId: 'b', explanation: 'Same bytecode runs on any JVM (any OS).' },
  { question: 'Interview: What does semantic analysis validate?', options: [{ id: 'a', text: 'Tokens only' }, { id: 'b', text: 'Types, scope, method signatures' }, { id: 'c', text: 'File size' }, { id: 'd', text: 'Network' }], correctOptionId: 'b', explanation: 'Semantic analysis checks types, scope, and signatures.' },
  { question: 'Interview: What is the constant pool?', options: [{ id: 'a', text: 'Heap area' }, { id: 'b', text: 'Part of .class with literals and references' }, { id: 'c', text: 'Stack' }, { id: 'd', text: 'GC pool' }], correctOptionId: 'b', explanation: 'Constant pool in .class holds literals and symbolic references.' },
  { question: 'Interview: Loading phase does what?', options: [{ id: 'a', text: 'Verify only' }, { id: 'b', text: 'Read .class and create Class object' }, { id: 'c', text: 'Run static blocks' }, { id: 'd', text: 'JIT' }], correctOptionId: 'b', explanation: 'Loading reads .class and creates the Class object.' },
  { question: 'Interview: Linking includes which sub-phases?', options: [{ id: 'a', text: 'Only load' }, { id: 'b', text: 'Verification, preparation, resolution' }, { id: 'c', text: 'Initialization only' }, { id: 'd', text: 'JIT only' }], correctOptionId: 'b', explanation: 'Linking = verification, preparation, resolution.' },
  { question: 'Interview: Who runs bytecode?', options: [{ id: 'a', text: 'javac' }, { id: 'b', text: 'JVM' }, { id: 'c', text: 'OS only' }, { id: 'd', text: 'Compiler' }], correctOptionId: 'b', explanation: 'JVM loads and runs bytecode (interpret + JIT).' },
  { question: 'Interview: Why bytecode instead of machine code?', options: [{ id: 'a', text: 'Faster' }, { id: 'b', text: 'Portability; one build runs everywhere' }, { id: 'c', text: 'Smaller' }, { id: 'd', text: 'Easier to write' }], correctOptionId: 'b', explanation: 'Bytecode enables "write once, run anywhere."' },
  { question: 'Interview: What follows bytecode generation?', options: [{ id: 'a', text: 'Lexical analysis' }, { id: 'b', text: 'JVM loads and executes .class' }, { id: 'c', text: 'Source edit' }, { id: 'd', text: 'Linking only' }], correctOptionId: 'b', explanation: 'After .class is produced, JVM loads and runs it.' },
  { question: 'Interview: What is verification (JVM)?', options: [{ id: 'a', text: 'Type check in compiler' }, { id: 'b', text: 'Checking bytecode safety/correctness during Linking' }, { id: 'c', text: 'Running tests' }, { id: 'd', text: 'Loading file' }], correctOptionId: 'b', explanation: 'Verification ensures bytecode is safe and well-formed.' },
  { question: 'Interview: Preparation (Linking) does what?', options: [{ id: 'a', text: 'Run static blocks' }, { id: 'b', text: 'Allocate memory for static fields' }, { id: 'c', text: 'Load file' }, { id: 'd', text: 'JIT' }], correctOptionId: 'b', explanation: 'Preparation allocates memory for class variables.' },
  { question: 'Interview: Resolution (Linking) does what?', options: [{ id: 'a', text: 'Load .class' }, { id: 'b', text: 'Resolve symbolic references to concrete refs' }, { id: 'c', text: 'Run main' }, { id: 'd', text: 'Verify only' }], correctOptionId: 'b', explanation: 'Resolution converts symbolic references into direct references.' },
  { question: 'Interview: What is "write once, run anywhere"?', options: [{ id: 'a', text: 'One source, one OS' }, { id: 'b', text: 'Compile once to bytecode; run on any platform with JVM' }, { id: 'c', text: 'One machine only' }, { id: 'd', text: 'Network only' }], correctOptionId: 'b', explanation: 'Bytecode runs on any JVM, so one build runs everywhere.' },
];

// Topic 2: Basic Syntax — 20 activities, 20 quiz (interview-aligned)
const basicSyntaxActivities = [
  { type: 'multiple-choice', instruction: 'Interview: Correct way to declare a method that returns int and takes no parameters?', options: [{ id: 'a', text: 'void method()' }, { id: 'b', text: 'int method()' }, { id: 'c', text: 'method int()' }, { id: 'd', text: 'int method(void)' }], correctAnswer: 'b', explanation: 'Return type first, then name, then ().' },
  { type: 'match-pairs', instruction: 'Interview: Match operator to meaning.', options: [{ id: 'mod', text: '%', correctMatch: 'rem' }, { id: 'and', text: '&&', correctMatch: 'land' }, { id: 'eq', text: '==', correctMatch: 'eq' }, { id: 'not', text: '!', correctMatch: 'lnot' }], matchOptions: [{ id: 'rem', text: 'Modulo (remainder)' }, { id: 'land', text: 'Logical AND' }, { id: 'eq', text: 'Equality' }, { id: 'lnot', text: 'Logical NOT' }], correctAnswer: [['mod', 'rem'], ['and', 'land'], ['eq', 'eq'], ['not', 'lnot']], explanation: '% modulo; && AND; == equality; ! NOT.' },
  { type: 'drag-order', instruction: 'Interview: Order of method declaration parts in Java.', options: [{ id: 'ret', text: 'Return type', correctOrder: 1 }, { id: 'name', text: 'Method name', correctOrder: 2 }, { id: 'params', text: 'Parameters in ()', correctOrder: 3 }], correctAnswer: ['ret', 'name', 'params'], explanation: 'Return type, name, then parameter list.' },
  { type: 'multiple-choice', instruction: 'Interview: Which is logical OR?', options: [{ id: 'a', text: '&' }, { id: 'b', text: '|' }, { id: 'c', text: '||' }, { id: 'd', text: 'or' }], correctAnswer: 'c', explanation: '|| is short-circuit logical OR.' },
  { type: 'match-pairs', instruction: 'Match control structure to use.', options: [{ id: 'if', text: 'if/else', correctMatch: 'cond' }, { id: 'for', text: 'for', correctMatch: 'loop' }, { id: 'switch', text: 'switch', correctMatch: 'multi' }], matchOptions: [{ id: 'cond', text: 'Conditional branching' }, { id: 'loop', text: 'Counted loop' }, { id: 'multi', text: 'Multiple values' }], correctAnswer: [['if', 'cond'], ['for', 'loop'], ['switch', 'multi']], explanation: 'if=branch; for=loop; switch=multi-way.' },
  { type: 'multiple-choice', instruction: 'Interview: Modulo operator?', options: [{ id: 'a', text: '/' }, { id: 'b', text: '%' }, { id: 'c', text: '//' }, { id: 'd', text: '&' }], correctAnswer: 'b', explanation: '% returns remainder.' },
  { type: 'multiple-choice', instruction: 'Interview: What does && do?', options: [{ id: 'a', text: 'Bitwise AND' }, { id: 'b', text: 'Logical AND (short-circuit)' }, { id: 'c', text: 'Append' }, { id: 'd', text: 'Reference' }], correctAnswer: 'b', explanation: '&& is logical AND; short-circuits if first is false.' },
  { type: 'drag-order', instruction: 'Order: arithmetic operators by precedence (same as Java).', options: [{ id: 'mul', text: '* / %', correctOrder: 1 }, { id: 'add', text: '+ -', correctOrder: 2 }], correctAnswer: ['mul', 'add'], explanation: '* / % before + -.' },
  { type: 'multiple-choice', instruction: 'Interview: Single-line comment in Java?', options: [{ id: 'a', text: '#' }, { id: 'b', text: '//' }, { id: 'c', text: '--' }, { id: 'd', text: ';;' }], correctAnswer: 'b', explanation: '// starts a single-line comment.' },
  { type: 'match-pairs', instruction: 'Match loop type to keyword.', options: [{ id: 'for', text: 'for', correctMatch: 'count' }, { id: 'while', text: 'while', correctMatch: 'pre' }, { id: 'do', text: 'do-while', correctMatch: 'post' }], matchOptions: [{ id: 'count', text: 'Counted / known iterations' }, { id: 'pre', text: 'Condition checked first' }, { id: 'post', text: 'Condition checked after body' }], correctAnswer: [['for', 'count'], ['while', 'pre'], ['do', 'post']], explanation: 'for=count; while=pre-check; do-while=post-check.' },
  { type: 'multiple-choice', instruction: 'Interview: Javadoc comment style?', options: [{ id: 'a', text: '//' }, { id: 'b', text: '/* */' }, { id: 'c', text: '/** */' }, { id: 'd', text: '#' }], correctAnswer: 'c', explanation: '/** */ is used for Javadoc.' },
  { type: 'multiple-choice', instruction: 'Interview: Comparison "not equal" operator?', options: [{ id: 'a', text: '<>' }, { id: 'b', text: '!=' }, { id: 'c', text: '=/=' }, { id: 'd', text: 'not' }], correctAnswer: 'b', explanation: '!= is not equal.' },
  { type: 'drag-order', instruction: 'Order: if / else if / else evaluation.', options: [{ id: 'if', text: 'if (condition)', correctOrder: 1 }, { id: 'elseif', text: 'else if (condition)', correctOrder: 2 }, { id: 'else', text: 'else', correctOrder: 3 }], correctAnswer: ['if', 'elseif', 'else'], explanation: 'First if, then else if, then else.' },
  { type: 'multiple-choice', instruction: 'Interview: Enhanced for loop syntax?', options: [{ id: 'a', text: 'for (x in list)' }, { id: 'b', text: 'for (Type x : collection)' }, { id: 'c', text: 'foreach (x : list)' }, { id: 'd', text: 'loop x in list' }], correctAnswer: 'b', explanation: 'for (Type var : iterable) is enhanced for.' },
  { type: 'match-pairs', instruction: 'Match operator category.', options: [{ id: 'plus', text: '+ - * /', correctMatch: 'ar' }, { id: 'eq', text: '== != < >', correctMatch: 'comp' }, { id: 'and', text: '&& || !', correctMatch: 'log' }], matchOptions: [{ id: 'ar', text: 'Arithmetic' }, { id: 'comp', text: 'Comparison' }, { id: 'log', text: 'Logical' }], correctAnswer: [['plus', 'ar'], ['eq', 'comp'], ['and', 'log']], explanation: 'Arithmetic, comparison, logical.' },
  { type: 'multiple-choice', instruction: 'Interview: Statement terminator in Java?', options: [{ id: 'a', text: 'Newline' }, { id: 'b', text: 'Semicolon (;)' }, { id: 'c', text: 'Colon' }, { id: 'd', text: 'Comma' }], correctAnswer: 'b', explanation: 'Statements end with ;' },
  { type: 'multiple-choice', instruction: 'Interview: Block delimiter?', options: [{ id: 'a', text: 'Indentation' }, { id: 'b', text: 'Curly braces {}' }, { id: 'c', text: 'Parentheses' }, { id: 'd', text: 'Keywords' }], correctAnswer: 'b', explanation: 'Blocks use { }.' },
  { type: 'drag-order', instruction: 'Order: method signature components.', options: [{ id: 'ret', text: 'Return type', correctOrder: 1 }, { id: 'name', text: 'Method name', correctOrder: 2 }, { id: 'args', text: 'Parameter list', correctOrder: 3 }], correctAnswer: ['ret', 'name', 'args'], explanation: 'Return type, name, (params).' },
  { type: 'multiple-choice', instruction: 'Interview: What is short-circuit evaluation?', options: [{ id: 'a', text: 'Faster CPU' }, { id: 'b', text: '&& and || stop evaluating once result is known' }, { id: 'c', text: 'Smaller bytecode' }, { id: 'd', text: 'Only for loops' }], correctAnswer: 'b', explanation: 'With && if first is false, second not evaluated; with || if first is true, second not evaluated.' },
  { type: 'multiple-choice', instruction: 'Interview: Which is assignment, which is equality?', options: [{ id: 'a', text: '= is assignment; == is equality' }, { id: 'b', text: '== is assignment' }, { id: 'c', text: 'Same thing' }, { id: 'd', text: ':= for assignment' }], correctAnswer: 'a', explanation: '= assigns; == compares for equality.' },
];

const basicSyntaxQuizzes = [
  { question: 'Interview: Order of method declaration?', options: [{ id: 'a', text: 'name, return type, params' }, { id: 'b', text: 'return type, name, params' }, { id: 'c', text: 'params, return type, name' }, { id: 'd', text: 'return type, params, name' }], correctOptionId: 'b', explanation: 'Return type, method name, then (params).' },
  { question: 'Interview: Modulo operator?', options: [{ id: 'a', text: '/' }, { id: 'b', text: '%' }, { id: 'c', text: '//' }, { id: 'd', text: '&' }], correctOptionId: 'b', explanation: '% is remainder.' },
  { question: 'Interview: Logical OR operator?', options: [{ id: 'a', text: '&' }, { id: 'b', text: '|' }, { id: 'c', text: '||' }, { id: 'd', text: 'or' }], correctOptionId: 'c', explanation: '|| is logical OR.' },
  { question: 'Interview: What ends a statement?', options: [{ id: 'a', text: 'Newline' }, { id: 'b', text: 'Semicolon' }, { id: 'c', text: 'Comma' }, { id: 'd', text: 'Space' }], correctOptionId: 'b', explanation: '; terminates statements.' },
  { question: 'Interview: What denotes a block?', options: [{ id: 'a', text: 'Indent' }, { id: 'b', text: 'Curly braces {}' }, { id: 'c', text: 'Parentheses' }, { id: 'd', text: 'Brackets' }], correctOptionId: 'b', explanation: 'Blocks use { }.' },
  { question: 'Interview: Difference between = and ==?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: '= assignment; == equality' }, { id: 'c', text: '== assignment' }, { id: 'd', text: ':= and =' }], correctOptionId: 'b', explanation: '= assigns; == compares.' },
  { question: 'Interview: Enhanced for loop?', options: [{ id: 'a', text: 'for (x in list)' }, { id: 'b', text: 'for (Type x : iterable)' }, { id: 'c', text: 'foreach' }, { id: 'd', text: 'loop' }], correctOptionId: 'b', explanation: 'for (Type var : iterable).' },
  { question: 'Interview: Short-circuit with &&?', options: [{ id: 'a', text: 'Always evaluate both' }, { id: 'b', text: 'If first is false, second not evaluated' }, { id: 'c', text: 'If first true, stop' }, { id: 'd', text: 'Never short-circuit' }], correctOptionId: 'b', explanation: '&& skips second if first is false.' },
  { question: 'Interview: Comment for documentation?', options: [{ id: 'a', text: '//' }, { id: 'b', text: '/** */' }, { id: 'c', text: '#' }, { id: 'd', text: '--' }], correctOptionId: 'b', explanation: '/** */ is Javadoc.' },
  { question: 'Interview: Not equal operator?', options: [{ id: 'a', text: '<>' }, { id: 'b', text: '!=' }, { id: 'c', text: '=/=' }, { id: 'd', text: 'not' }], correctOptionId: 'b', explanation: '!= is not equal.' },
  { question: 'Interview: do-while vs while?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'do-while body runs at least once' }, { id: 'c', text: 'while runs twice' }, { id: 'd', text: 'No do-while in Java' }], correctOptionId: 'b', explanation: 'do-while checks condition after body.' },
  { question: 'Interview: switch can use which types?', options: [{ id: 'a', text: 'Only int' }, { id: 'b', text: 'int, enum, String, wrappers (and compatible)' }, { id: 'c', text: 'Any' }, { id: 'd', text: 'Only String' }], correctOptionId: 'b', explanation: 'switch supports int, enum, String, and compatible types.' },
  { question: 'Interview: Arithmetic operator for remainder?', options: [{ id: 'a', text: '/' }, { id: 'b', text: '%' }, { id: 'c', text: '//' }, { id: 'd', text: 'rem' }], correctOptionId: 'b', explanation: '% is modulo.' },
  { question: 'Interview: Logical NOT?', options: [{ id: 'a', text: 'NOT' }, { id: 'b', text: '!' }, { id: 'c', text: '~' }, { id: 'd', text: '-' }], correctOptionId: 'b', explanation: '! is logical NOT.' },
  { question: 'Interview: Method that returns nothing?', options: [{ id: 'a', text: 'null' }, { id: 'b', text: 'void' }, { id: 'c', text: 'none' }, { id: 'd', text: 'empty' }], correctOptionId: 'b', explanation: 'void means no return value.' },
  { question: 'Interview: for (;;) means?', options: [{ id: 'a', text: 'Syntax error' }, { id: 'b', text: 'Infinite loop' }, { id: 'c', text: 'No loop' }, { id: 'd', text: 'Zero iterations' }], correctOptionId: 'b', explanation: 'Empty condition is true; infinite loop.' },
  { question: 'Interview: Comparison >= means?', options: [{ id: 'a', text: 'Greater only' }, { id: 'b', text: 'Greater or equal' }, { id: 'c', text: 'Equal only' }, { id: 'd', text: 'Assign then compare' }], correctOptionId: 'b', explanation: '>= is greater than or equal.' },
  { question: 'Interview: Multi-line comment?', options: [{ id: 'a', text: '// only' }, { id: 'b', text: '/* */' }, { id: 'c', text: '#' }, { id: 'd', text: '--' }], correctOptionId: 'b', explanation: '/* */ is multi-line comment.' },
  { question: 'Interview: Correct method with one int parameter?', options: [{ id: 'a', text: 'method(int x)' }, { id: 'b', text: 'void method(int x)' }, { id: 'c', text: 'method int x' }, { id: 'd', text: 'method(int x) void' }], correctOptionId: 'b', explanation: 'Return type, name, (params).' },
  { question: 'Interview: What is &&?', options: [{ id: 'a', text: 'Bitwise AND' }, { id: 'b', text: 'Logical AND' }, { id: 'c', text: 'Reference' }, { id: 'd', text: 'Append' }], correctOptionId: 'b', explanation: '&& is logical AND.' },
];

// Topic 3: Variables and Data Types — 20 activities, 20 quiz
const variablesActivities = [
  { type: 'match-pairs', instruction: 'Interview: Match type to use.', options: [{ id: 'int', text: 'int', correctMatch: 'w' }, { id: 'double', text: 'double', correctMatch: 'd' }, { id: 'boolean', text: 'boolean', correctMatch: 'b' }, { id: 'char', text: 'char', correctMatch: 'c' }], matchOptions: [{ id: 'w', text: 'Whole numbers' }, { id: 'd', text: 'Decimals' }, { id: 'b', text: 'true/false' }, { id: 'c', text: 'Single character' }], correctAnswer: [['int', 'w'], ['double', 'd'], ['boolean', 'b'], ['char', 'c']], explanation: 'int=whole; double=decimal; boolean=logic; char=one char.' },
  { type: 'multiple-choice', instruction: 'Interview: Default value of uninitialized local variable?', options: [{ id: 'a', text: '0 or false' }, { id: 'b', text: 'None; must initialize before use' }, { id: 'c', text: 'null' }, { id: 'd', text: 'Random' }], correctAnswer: 'b', explanation: 'Locals must be initialized; no default.' },
  { type: 'multiple-choice', instruction: 'Interview: Why use L in long literal?', options: [{ id: 'a', text: 'Optional' }, { id: 'b', text: 'Without L, literal is int and may be out of range' }, { id: 'c', text: 'Makes unsigned' }, { id: 'd', text: 'Long only' }], correctAnswer: 'b', explanation: 'Integer literals are int by default; L makes it long.' },
  { type: 'drag-order', instruction: 'Order: primitive integer types by size (bytes).', options: [{ id: 'b', text: 'byte (1)', correctOrder: 1 }, { id: 's', text: 'short (2)', correctOrder: 2 }, { id: 'i', text: 'int (4)', correctOrder: 3 }, { id: 'l', text: 'long (8)', correctOrder: 4 }], correctAnswer: ['b', 's', 'i', 'l'], explanation: 'byte < short < int < long.' },
  { type: 'match-pairs', instruction: 'Match scope to where declared.', options: [{ id: 'inst', text: 'Instance variable', correctMatch: 'class' }, { id: 'local', text: 'Local variable', correctMatch: 'method' }, { id: 'stat', text: 'Static variable', correctMatch: 'shared' }], matchOptions: [{ id: 'class', text: 'Inside class, outside method' }, { id: 'method', text: 'Inside method or block' }, { id: 'shared', text: 'static; shared by all instances' }], correctAnswer: [['inst', 'class'], ['local', 'method'], ['stat', 'shared']], explanation: 'Instance=class level; Local=method/block; Static=shared.' },
  { type: 'multiple-choice', instruction: 'Interview: Widening casting?', options: [{ id: 'a', text: 'Larger to smaller' }, { id: 'b', text: 'Smaller to larger (e.g. int to long); automatic' }, { id: 'c', text: 'Primitive to reference' }, { id: 'd', text: 'String to int' }], correctAnswer: 'b', explanation: 'Widening = smaller to larger; implicit.' },
  { type: 'multiple-choice', instruction: 'Interview: Narrowing casting?', options: [{ id: 'a', text: 'Automatic' }, { id: 'b', text: 'Larger to smaller; requires explicit cast' }, { id: 'c', text: 'Only for int' }, { id: 'd', text: 'Not in Java' }], correctAnswer: 'b', explanation: 'Narrowing needs (Type) and may lose data.' },
  { type: 'drag-order', instruction: 'Order: floating-point types by precision.', options: [{ id: 'f', text: 'float (4 bytes)', correctOrder: 1 }, { id: 'd', text: 'double (8 bytes)', correctOrder: 2 }], correctAnswer: ['f', 'd'], explanation: 'float then double (double has more precision).' },
  { type: 'multiple-choice', instruction: 'Interview: String is primitive?', options: [{ id: 'a', text: 'Yes' }, { id: 'b', text: 'No; reference type (class)' }, { id: 'c', text: 'Sometimes' }, { id: 'd', text: 'Only in arrays' }], correctAnswer: 'b', explanation: 'String is a reference type (class).' },
  { type: 'match-pairs', instruction: 'Match literal suffix to type.', options: [{ id: 'L', text: 'L', correctMatch: 'long' }, { id: 'f', text: 'f', correctMatch: 'float' }, { id: 'd', text: 'd', correctMatch: 'double' }], matchOptions: [{ id: 'long', text: 'long' }, { id: 'float', text: 'float' }, { id: 'double', text: 'double' }], correctAnswer: [['L', 'long'], ['f', 'float'], ['d', 'double']], explanation: 'L=long; f=float; d=double (optional).' },
  { type: 'multiple-choice', instruction: 'Interview: Default value of instance int field?', options: [{ id: 'a', text: 'Unset' }, { id: 'b', text: '0' }, { id: 'c', text: 'null' }, { id: 'd', text: 'Compiler error' }], correctAnswer: 'b', explanation: 'Instance/static fields get default (0, false, null).' },
  { type: 'multiple-choice', instruction: 'Interview: char size in Java?', options: [{ id: 'a', text: '1 byte' }, { id: 'b', text: '2 bytes (Unicode)' }, { id: 'c', text: '4 bytes' }, { id: 'd', text: 'Variable' }], correctAnswer: 'b', explanation: 'char is 16-bit Unicode.' },
  { type: 'drag-order', instruction: 'Order: declaration then assignment.', options: [{ id: 'decl', text: 'Declare type and name', correctOrder: 1 }, { id: 'assign', text: 'Assign value (optional at first)', correctOrder: 2 }], correctAnswer: ['decl', 'assign'], explanation: 'Declare first, then optionally assign.' },
  { type: 'multiple-choice', instruction: 'Interview: boolean possible values?', options: [{ id: 'a', text: '0 and 1' }, { id: 'b', text: 'true and false only' }, { id: 'c', text: 'Any number' }, { id: 'd', text: 'null' }], correctAnswer: 'b', explanation: 'boolean is only true or false.' },
  { type: 'match-pairs', instruction: 'Match type to default value (fields).', options: [{ id: 'int', text: 'int', correctMatch: 'zero' }, { id: 'bool', text: 'boolean', correctMatch: 'false' }, { id: 'ref', text: 'reference', correctMatch: 'null' }], matchOptions: [{ id: 'zero', text: '0' }, { id: 'false', text: 'false' }, { id: 'null', text: 'null' }], correctAnswer: [['int', 'zero'], ['bool', 'false'], ['ref', 'null']], explanation: 'int=0; boolean=false; reference=null.' },
  { type: 'multiple-choice', instruction: 'Interview: final variable?', options: [{ id: 'a', text: 'Must be static' }, { id: 'b', text: 'Cannot be reassigned after initial assignment' }, { id: 'c', text: 'Only for primitives' }, { id: 'd', text: 'Same as const' }], correctAnswer: 'b', explanation: 'final means assign once.' },
  { type: 'multiple-choice', instruction: 'Interview: Type of 3.14?', options: [{ id: 'a', text: 'float' }, { id: 'b', text: 'double' }, { id: 'c', text: 'int' }, { id: 'd', text: 'Object' }], correctAnswer: 'b', explanation: 'Floating-point literal is double by default.' },
  { type: 'drag-order', instruction: 'Order: widening order for integers.', options: [{ id: 'b', text: 'byte', correctOrder: 1 }, { id: 's', text: 'short', correctOrder: 2 }, { id: 'i', text: 'int', correctOrder: 3 }, { id: 'l', text: 'long', correctOrder: 4 }], correctAnswer: ['b', 's', 'i', 'l'], explanation: 'Widening: byte→short→int→long.' },
  { type: 'multiple-choice', instruction: 'Interview: Can int hold decimal?', options: [{ id: 'a', text: 'Yes' }, { id: 'b', text: 'No; use double/float for decimals' }, { id: 'c', text: 'Only with cast' }, { id: 'd', text: 'Only negative' }], correctAnswer: 'b', explanation: 'int is whole numbers only.' },
  { type: 'multiple-choice', instruction: 'Interview: Variable naming: can start with digit?', options: [{ id: 'a', text: 'Yes' }, { id: 'b', text: 'No; must start with letter, _, or $' }, { id: 'c', text: 'Only for numbers' }, { id: 'd', text: 'Only static' }], correctAnswer: 'b', explanation: 'Identifier cannot start with a digit.' },
];

const variablesQuizzes = [
  { question: 'Interview: Type for true/false?', options: [{ id: 'a', text: 'int' }, { id: 'b', text: 'boolean' }, { id: 'c', text: 'byte' }, { id: 'd', text: 'String' }], correctOptionId: 'b', explanation: 'boolean is for true/false.' },
  { question: 'Interview: Why 15000000000L?', options: [{ id: 'a', text: 'Optional' }, { id: 'b', text: 'Without L, literal is int and out of range' }, { id: 'c', text: 'Unsigned' }, { id: 'd', text: 'Long only' }], correctOptionId: 'b', explanation: 'L makes it a long literal.' },
  { question: 'Interview: What is widening?', options: [{ id: 'a', text: 'Larger to smaller' }, { id: 'b', text: 'Smaller to larger type; automatic' }, { id: 'c', text: 'Primitive to ref' }, { id: 'd', text: 'String to number' }], correctOptionId: 'b', explanation: 'Widening = smaller→larger; implicit.' },
  { question: 'Interview: Default for uninitialized local?', options: [{ id: 'a', text: '0/false/null' }, { id: 'b', text: 'Must initialize; no default' }, { id: 'c', text: 'null' }, { id: 'd', text: 'Random' }], correctOptionId: 'b', explanation: 'Locals have no default.' },
  { question: 'Interview: Instance variable scope?', options: [{ id: 'a', text: 'Only in one method' }, { id: 'b', text: 'Inside class, outside method; per object' }, { id: 'c', text: 'Global' }, { id: 'd', text: 'Only static' }], correctOptionId: 'b', explanation: 'Instance = class-level, one per object.' },
  { question: 'Interview: Static variable?', options: [{ id: 'a', text: 'One per object' }, { id: 'b', text: 'Shared by all instances' }, { id: 'c', text: 'Only in method' }, { id: 'd', text: 'Constant only' }], correctOptionId: 'b', explanation: 'static = one per class, shared.' },
  { question: 'Interview: Narrowing cast?', options: [{ id: 'a', text: 'Automatic' }, { id: 'b', text: 'Explicit (Type) required; may lose data' }, { id: 'c', text: 'Only int' }, { id: 'd', text: 'Not allowed' }], correctOptionId: 'b', explanation: 'Narrowing needs explicit cast.' },
  { question: 'Interview: String primitive?', options: [{ id: 'a', text: 'Yes' }, { id: 'b', text: 'No; reference type' }, { id: 'c', text: 'Sometimes' }, { id: 'd', text: 'In arrays only' }], correctOptionId: 'b', explanation: 'String is a class (reference type).' },
  { question: 'Interview: float literal suffix?', options: [{ id: 'a', text: 'L' }, { id: 'b', text: 'f' }, { id: 'c', text: 'd' }, { id: 'd', text: 'F' }], correctOptionId: 'b', explanation: 'f or F for float (e.g. 5.75f).' },
  { question: 'Interview: Default of boolean field?', options: [{ id: 'a', text: 'true' }, { id: 'b', text: 'false' }, { id: 'c', text: 'null' }, { id: 'd', text: 'Unset' }], correctOptionId: 'b', explanation: 'Default for boolean is false.' },
  { question: 'Interview: char size?', options: [{ id: 'a', text: '1 byte' }, { id: 'b', text: '2 bytes' }, { id: 'c', text: '4 bytes' }, { id: 'd', text: 'Variable' }], correctOptionId: 'b', explanation: 'char is 16-bit Unicode.' },
  { question: 'Interview: final variable?', options: [{ id: 'a', text: 'Must be static' }, { id: 'b', text: 'Assign once; cannot reassign' }, { id: 'c', text: 'Only primitives' }, { id: 'd', text: 'Constant only' }], correctOptionId: 'b', explanation: 'final = single assignment.' },
  { question: 'Interview: Type of 42?', options: [{ id: 'a', text: 'long' }, { id: 'b', text: 'int' }, { id: 'c', text: 'byte' }, { id: 'd', text: 'Integer' }], correctOptionId: 'b', explanation: 'Integer literal is int by default.' },
  { question: 'Interview: Reference type default (field)?', options: [{ id: 'a', text: '0' }, { id: 'b', text: 'null' }, { id: 'c', text: 'empty' }, { id: 'd', text: 'undefined' }], correctOptionId: 'b', explanation: 'Object fields default to null.' },
  { question: 'Interview: int hold 3.14?', options: [{ id: 'a', text: 'Yes' }, { id: 'b', text: 'No; truncation with cast' }, { id: 'c', text: 'Auto round' }, { id: 'd', text: 'Only positive' }], correctOptionId: 'b', explanation: 'int is integer; need double/float for 3.14.' },
  { question: 'Interview: Identifier can start with?', options: [{ id: 'a', text: 'Digit' }, { id: 'b', text: 'Letter, _, or $' }, { id: 'c', text: 'Any' }, { id: 'd', text: 'Only letter' }], correctOptionId: 'b', explanation: 'Must start with letter, _, or $.' },
  { question: 'Interview: long range vs int?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'long is larger range (64-bit)' }, { id: 'c', text: 'int larger' }, { id: 'd', text: 'long is unsigned' }], correctOptionId: 'b', explanation: 'long is 64-bit; int 32-bit.' },
  { question: 'Interview: Type casting (double to int)?', options: [{ id: 'a', text: 'Automatic' }, { id: 'b', text: 'Explicit (int) required; truncates' }, { id: 'c', text: 'Round automatically' }, { id: 'd', text: 'Not allowed' }], correctOptionId: 'b', explanation: 'Narrowing; explicit cast; decimal lost.' },
  { question: 'Interview: Where is local variable visible?', options: [{ id: 'a', text: 'Everywhere' }, { id: 'b', text: 'Only within method/block' }, { id: 'c', text: 'Whole class' }, { id: 'd', text: 'Static only' }], correctOptionId: 'b', explanation: 'Local = method/block scope only.' },
  { question: 'Interview: 3.14f type?', options: [{ id: 'a', text: 'double' }, { id: 'b', text: 'float' }, { id: 'c', text: 'int' }, { id: 'd', text: 'Long' }], correctOptionId: 'b', explanation: 'f suffix makes it float.' },
];

// Topic 4: Garbage Collection — 20 activities, 20 quiz
const gcActivities = [
  { type: 'drag-order', instruction: 'Interview: Order heap areas (object lifecycle).', options: [{ id: 'eden', text: 'Eden', correctOrder: 1 }, { id: 'surv', text: 'Survivor', correctOrder: 2 }, { id: 'old', text: 'Old Gen', correctOrder: 3 }], correctAnswer: ['eden', 'surv', 'old'], explanation: 'Eden → Survivor → Old Generation.' },
  { type: 'multiple-choice', instruction: 'Interview: When is object eligible for GC?', options: [{ id: 'a', text: 'When you set ref to null' }, { id: 'b', text: 'When no live thread can reach it' }, { id: 'c', text: 'After 5 minutes' }, { id: 'd', text: 'When System.gc() called' }], correctAnswer: 'b', explanation: 'Eligible when unreachable.' },
  { type: 'multiple-choice', instruction: 'Interview: SoftReference vs WeakReference?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Soft cleared when memory needed; Weak in next GC' }, { id: 'c', text: 'Weak stronger' }, { id: 'd', text: 'Weak never cleared' }], correctAnswer: 'b', explanation: 'Soft=memory pressure; Weak=next GC.' },
  { type: 'match-pairs', instruction: 'Match reference type to behavior.', options: [{ id: 'strong', text: 'Strong', correctMatch: 's1' }, { id: 'soft', text: 'Soft', correctMatch: 's2' }, { id: 'weak', text: 'Weak', correctMatch: 's3' }], matchOptions: [{ id: 's1', text: 'Normal; GC when unreachable' }, { id: 's2', text: 'Cleared before OOM (e.g. caches)' }, { id: 's3', text: 'Collected next GC' }], correctAnswer: [['strong', 's1'], ['soft', 's2'], ['weak', 's3']], explanation: 'Strong=normal; Soft=memory; Weak=next GC.' },
  { type: 'multiple-choice', instruction: 'Interview: Default GC in Java 17+?', options: [{ id: 'a', text: 'Parallel' }, { id: 'b', text: 'G1' }, { id: 'c', text: 'ZGC' }, { id: 'd', text: 'Serial' }], correctAnswer: 'b', explanation: 'G1 is default in Java 17+.' },
  { type: 'drag-order', instruction: 'Order: Minor GC then Major GC.', options: [{ id: 'minor', text: 'Minor GC (Eden + Survivor)', correctOrder: 1 }, { id: 'major', text: 'Major/Full GC (Old Gen)', correctOrder: 2 }], correctAnswer: ['minor', 'major'], explanation: 'Minor first (young); Major (old).' },
  { type: 'multiple-choice', instruction: 'Interview: Who frees object memory?', options: [{ id: 'a', text: 'Programmer' }, { id: 'b', text: 'JVM (GC)' }, { id: 'c', text: 'OS' }, { id: 'd', text: 'Compiler' }], correctAnswer: 'b', explanation: 'JVM GC reclaims unreachable objects.' },
  { type: 'match-pairs', instruction: 'Match collector to trait.', options: [{ id: 'g1', text: 'G1', correctMatch: 'reg' }, { id: 'zgc', text: 'ZGC', correctMatch: 'low' }, { id: 'par', text: 'Parallel', correctMatch: 'through' }], matchOptions: [{ id: 'reg', text: 'Region-based; low pause' }, { id: 'low', text: 'Very low pause' }, { id: 'through', text: 'Throughput-focused' }], correctAnswer: [['g1', 'reg'], ['zgc', 'low'], ['par', 'through']], explanation: 'G1=region; ZGC=low pause; Parallel=throughput.' },
  { type: 'multiple-choice', instruction: 'Interview: System.gc() guarantee collection?', options: [{ id: 'a', text: 'Yes, immediate' }, { id: 'b', text: 'No; hint only; JVM may ignore' }, { id: 'c', text: 'Only in dev' }, { id: 'd', text: 'Only for Soft refs' }], correctAnswer: 'b', explanation: 'System.gc() is a hint, not guarantee.' },
  { type: 'multiple-choice', instruction: 'Interview: Memory leak in Java?', options: [{ id: 'a', text: 'Impossible' }, { id: 'b', text: 'Possible; objects still reachable (e.g. static map)' }, { id: 'c', text: 'Only with native code' }, { id: 'd', text: 'Only with threads' }], correctAnswer: 'b', explanation: 'Leak = reachable but not needed (e.g. caches).' },
  { type: 'drag-order', instruction: 'Order: object allocation flow.', options: [{ id: 'new', text: 'new Object()', correctOrder: 1 }, { id: 'eden', text: 'Allocated in Eden', correctOrder: 2 }, { id: 'surv', text: 'May move to Survivor', correctOrder: 3 }, { id: 'old', text: 'May promote to Old', correctOrder: 4 }], correctAnswer: ['new', 'eden', 'surv', 'old'], explanation: 'new → Eden → Survivor → Old.' },
  { type: 'multiple-choice', instruction: 'Interview: PhantomReference use?', options: [{ id: 'a', text: 'Caching' }, { id: 'b', text: 'Cleanup/finalization; cannot get referent' }, { id: 'c', text: 'Strong ref' }, { id: 'd', text: 'Faster GC' }], correctAnswer: 'b', explanation: 'Phantom for cleanup; referent not accessible.' },
  { type: 'match-pairs', instruction: 'Match heap area to role.', options: [{ id: 'eden', text: 'Eden', correctMatch: 'e1' }, { id: 'surv', text: 'Survivor', correctMatch: 'e2' }, { id: 'old', text: 'Old Gen', correctMatch: 'e3' }], matchOptions: [{ id: 'e1', text: 'Most new allocations' }, { id: 'e2', text: 'Survivors of Minor GC' }, { id: 'e3', text: 'Long-lived objects' }], correctAnswer: [['eden', 'e1'], ['surv', 'e2'], ['old', 'e3']], explanation: 'Eden=new; Survivor=survivors; Old=long-lived.' },
  { type: 'multiple-choice', instruction: 'Interview: try-with-resources helps with?', options: [{ id: 'a', text: 'GC only' }, { id: 'b', text: 'Closing resources; avoids leaks' }, { id: 'c', text: 'Memory size' }, { id: 'd', text: 'Threads' }], correctAnswer: 'b', explanation: 'Ensures close() called; prevents resource leaks.' },
  { type: 'multiple-choice', instruction: 'Interview: WeakHashMap use case?', options: [{ id: 'a', text: 'Faster Map' }, { id: 'b', text: "Keys can be GC'd when no other refs" }, { id: 'c', text: 'Thread-safe only' }, { id: 'd', text: 'Sorted' }], correctAnswer: 'b', explanation: "Keys are weak refs; entries removed when key GC'd." },
  { type: 'drag-order', instruction: 'Order: GC pause types (typical impact).', options: [{ id: 'minor', text: 'Minor GC (short)', correctOrder: 1 }, { id: 'major', text: 'Full GC (longer)', correctOrder: 2 }], correctAnswer: ['minor', 'major'], explanation: 'Minor usually shorter than Full GC.' },
  { type: 'multiple-choice', instruction: 'Interview: What triggers Minor GC?', options: [{ id: 'a', text: 'Time only' }, { id: 'b', text: 'Eden full (typically)' }, { id: 'c', text: 'Old Gen full' }, { id: 'd', text: 'Manual only' }], correctAnswer: 'b', explanation: 'When Eden is full, Minor GC runs.' },
  { type: 'match-pairs', instruction: 'Match term to meaning.', options: [{ id: 'reach', text: 'Reachable', correctMatch: 'r1' }, { id: 'eligible', text: 'Eligible for GC', correctMatch: 'r2' }], matchOptions: [{ id: 'r1', text: 'Some live ref exists' }, { id: 'r2', text: 'No live ref; can be collected' }], correctAnswer: [['reach', 'r1'], ['eligible', 'r2']], explanation: 'Reachable=has ref; Eligible=no refs.' },
  { type: 'multiple-choice', instruction: 'Interview: G1 stands for?', options: [{ id: 'a', text: 'General' }, { id: 'b', text: 'Garbage-First' }, { id: 'c', text: 'Generation 1' }, { id: 'd', text: 'Global' }], correctAnswer: 'b', explanation: 'Garbage-First collector.' },
  { type: 'multiple-choice', instruction: 'Interview: ZGC goal?', options: [{ id: 'a', text: 'Throughput only' }, { id: 'b', text: 'Very low pause times' }, { id: 'c', text: 'Small heap only' }, { id: 'd', text: 'No compaction' }], correctAnswer: 'b', explanation: 'ZGC targets sub-ms pauses.' },
];

const gcQuizzes = [
  { question: 'Interview: Who frees object memory?', options: [{ id: 'a', text: 'Programmer' }, { id: 'b', text: 'JVM (GC)' }, { id: 'c', text: 'OS' }, { id: 'd', text: 'Compiler' }], correctOptionId: 'b', explanation: 'GC reclaims unreachable objects.' },
  { question: 'Interview: SoftReference vs WeakReference?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Soft when memory needed; Weak next GC' }, { id: 'c', text: 'Weak stronger' }, { id: 'd', text: 'Weak never cleared' }], correctOptionId: 'b', explanation: 'Soft=memory pressure; Weak=next GC.' },
  { question: 'Interview: Default GC Java 17+?', options: [{ id: 'a', text: 'Parallel' }, { id: 'b', text: 'G1' }, { id: 'c', text: 'ZGC' }, { id: 'd', text: 'Serial' }], correctOptionId: 'b', explanation: 'G1 is default.' },
  { question: 'Interview: When eligible for GC?', options: [{ id: 'a', text: 'When null' }, { id: 'b', text: 'When unreachable' }, { id: 'c', text: 'After time' }, { id: 'd', text: 'System.gc() only' }], correctOptionId: 'b', explanation: 'Eligible when no refs.' },
  { question: 'Interview: Eden full triggers?', options: [{ id: 'a', text: 'Full GC' }, { id: 'b', text: 'Minor GC' }, { id: 'c', text: 'Nothing' }, { id: 'd', text: 'JIT' }], correctOptionId: 'b', explanation: 'Minor GC when Eden full.' },
  { question: 'Interview: Strong reference?', options: [{ id: 'a', text: 'Cleared soon' }, { id: 'b', text: 'Normal ref; GC when unreachable' }, { id: 'c', text: 'Weak' }, { id: 'd', text: 'Phantom' }], correctOptionId: 'b', explanation: 'Strong = normal; prevents GC while reachable.' },
  { question: 'Interview: PhantomReference?', options: [{ id: 'a', text: 'Strong' }, { id: 'b', text: 'For cleanup; cannot get referent' }, { id: 'c', text: 'For caching' }, { id: 'd', text: 'Same as Weak' }], correctOptionId: 'b', explanation: 'Phantom for finalization/cleanup.' },
  { question: 'Interview: Memory leak in Java?', options: [{ id: 'a', text: 'Impossible' }, { id: 'b', text: 'Possible; retained refs' }, { id: 'c', text: 'Only native' }, { id: 'd', text: 'Only threads' }], correctOptionId: 'b', explanation: 'Leak = still reachable but not needed.' },
  { question: 'Interview: System.gc()?', options: [{ id: 'a', text: 'Forces immediate GC' }, { id: 'b', text: 'Hint only; JVM may ignore' }, { id: 'c', text: 'Required' }, { id: 'd', text: 'Only Minor' }], correctOptionId: 'b', explanation: 'Hint only, not guarantee.' },
  { question: 'Interview: Survivor space?', options: [{ id: 'a', text: 'Where dead objects go' }, { id: 'b', text: 'Objects that survived Minor GC' }, { id: 'c', text: 'Static only' }, { id: 'd', text: 'Old Gen' }], correctOptionId: 'b', explanation: 'Survivors of Minor GC.' },
  { question: 'Interview: Old Generation?', options: [{ id: 'a', text: 'New objects' }, { id: 'b', text: 'Long-lived; Major/Full GC' }, { id: 'c', text: 'Stack' }, { id: 'd', text: 'Method area' }], correctOptionId: 'b', explanation: 'Old Gen = long-lived; Full GC.' },
  { question: 'Interview: try-with-resources?', options: [{ id: 'a', text: 'GC only' }, { id: 'b', text: 'Auto close; avoid leaks' }, { id: 'c', text: 'Memory' }, { id: 'd', text: 'Threads' }], correctOptionId: 'b', explanation: 'Ensures resources closed.' },
  { question: 'Interview: WeakHashMap?', options: [{ id: 'a', text: 'Faster' }, { id: 'b', text: 'Keys weakly referenced' }, { id: 'c', text: 'Thread-safe' }, { id: 'd', text: 'Sorted' }], correctOptionId: 'b', explanation: 'Keys can be GC\'d.' },
  { question: 'Interview: G1 collector?', options: [{ id: 'a', text: 'Serial' }, { id: 'b', text: 'Region-based; low pause' }, { id: 'c', text: 'ZGC' }, { id: 'd', text: 'Parallel only' }], correctOptionId: 'b', explanation: 'G1 = region-based.' },
  { question: 'Interview: ZGC goal?', options: [{ id: 'a', text: 'Throughput' }, { id: 'b', text: 'Low pause' }, { id: 'c', text: 'Small heap' }, { id: 'd', text: 'No compaction' }], correctOptionId: 'b', explanation: 'Sub-ms pause goal.' },
  { question: 'Interview: Promotion in GC?', options: [{ id: 'a', text: 'Eden to Survivor' }, { id: 'b', text: 'Moving to Old Gen after surviving' }, { id: 'c', text: 'Ref only' }, { id: 'd', text: 'Stack' }], correctOptionId: 'b', explanation: 'Promotion = to Old Gen.' },
  { question: 'Interview: Minor vs Full GC?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Minor=young; Full=whole heap' }, { id: 'c', text: 'Minor=old' }, { id: 'd', text: 'Full=young' }], correctOptionId: 'b', explanation: 'Minor=young gen; Full=entire heap.' },
  { question: 'Interview: Reachable object?', options: [{ id: 'a', text: 'Always collected' }, { id: 'b', text: 'Has live reference; not collected' }, { id: 'c', text: 'Only in Eden' }, { id: 'd', text: 'Only static' }], correctOptionId: 'b', explanation: 'Reachable = has ref; not eligible.' },
  { question: 'Interview: Clear reference when done?', options: [{ id: 'a', text: 'Never needed' }, { id: 'b', text: 'Good practice; helps GC' }, { id: 'c', text: 'Only for primitives' }, { id: 'd', text: 'Forces GC' }], correctOptionId: 'b', explanation: 'Clearing refs helps GC reclaim.' },
  { question: 'Interview: Parallel collector?', options: [{ id: 'a', text: 'Single-threaded' }, { id: 'b', text: 'Multi-threaded; throughput' }, { id: 'c', text: 'Low pause only' }, { id: 'd', text: 'Default in 17+' }], correctOptionId: 'b', explanation: 'Parallel = multi-threaded throughput.' },
];

// Helper: 20 interview pairs → 20 activities + 20 quiz (aligned: same concept per pair)
function buildFromPairs(pairs) {
  const activities = pairs.map((p) => ({
    type: 'multiple-choice',
    instruction: p.instruction || ('Interview: ' + p.question),
    options: p.options.map((o) => ({ id: o.id, text: o.text })),
    correctAnswer: p.correctAnswer,
    explanation: p.explanation,
  }));
  const quizQuestions = pairs.map((p) => ({
    question: p.question,
    options: p.options.map((o) => ({ id: o.id, text: o.text })),
    correctOptionId: p.correctOptionId || p.correctAnswer,
    explanation: p.explanation,
  }));
  return { activities, quizQuestions };
}

// Topic 5: Classes and Objects — 20 interview pairs
const classesPairs = [
  { question: 'Interview: Class vs object?', instruction: 'Interview: Difference between class and object?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Class=blueprint; object=instance' }, { id: 'c', text: 'Object=template' }, { id: 'd', text: 'Class=data only' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Class=template; object=concrete instance.' },
  { question: 'Interview: Keyword to create instance?', instruction: 'Interview: Which keyword creates an instance?', options: [{ id: 'a', text: 'create' }, { id: 'b', text: 'new' }, { id: 'c', text: 'instance' }, { id: 'd', text: 'object' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'new allocates and calls constructor.' },
  { question: 'Interview: Multiple constructors?', instruction: 'Interview: Can a class have multiple constructors?', options: [{ id: 'a', text: 'No' }, { id: 'b', text: 'Yes; overloading (different params)' }, { id: 'c', text: 'Only different return' }, { id: 'd', text: 'Only in abstract' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Constructor overloading allowed.' },
  { question: 'Interview: Instance variables hold?', instruction: 'Interview: What do instance variables hold?', options: [{ id: 'a', text: 'Constants only' }, { id: 'b', text: 'State of each object' }, { id: 'c', text: 'Shared data only' }, { id: 'd', text: 'Methods' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Instance vars = object state.' },
  { question: 'Interview: Constructor name?', instruction: 'Interview: Constructor name must be?', options: [{ id: 'a', text: 'constructor' }, { id: 'b', text: 'Same as class name' }, { id: 'c', text: 'init' }, { id: 'd', text: 'Any' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Constructor name = class name.' },
  { question: 'Interview: Object created when?', instruction: 'Interview: When is an object created?', options: [{ id: 'a', text: 'Compile time' }, { id: 'b', text: 'Runtime with new' }, { id: 'c', text: 'Class load' }, { id: 'd', text: 'Never' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Objects created at runtime.' },
  { question: 'Interview: Attribute vs method?', instruction: 'Interview: Attribute vs method?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Attribute=state; method=behavior' }, { id: 'c', text: 'Method=state' }, { id: 'd', text: 'Attribute=behavior' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Attributes=state; methods=behavior.' },
  { question: 'Interview: Default constructor?', instruction: 'Interview: When is default constructor provided?', options: [{ id: 'a', text: 'Never' }, { id: 'b', text: 'Only if no other constructor' }, { id: 'c', text: 'Always' }, { id: 'd', text: 'Only abstract' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Compiler adds no-arg if none defined.' },
  { question: 'Interview: this keyword?', instruction: 'Interview: What does this refer to?', options: [{ id: 'a', text: 'Superclass' }, { id: 'b', text: 'Current object' }, { id: 'c', text: 'Class' }, { id: 'd', text: 'Parent' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'this = current object reference.' },
  { question: 'Interview: Constructor return type?', instruction: 'Interview: Can constructor have return type?', options: [{ id: 'a', text: 'Yes any' }, { id: 'b', text: 'No return type' }, { id: 'c', text: 'Only void' }, { id: 'd', text: 'Only int' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Constructors have no return type.' },
  { question: 'Interview: How many objects from one class?', instruction: 'Interview: How many objects from one class?', options: [{ id: 'a', text: 'One' }, { id: 'b', text: 'Many (each own state)' }, { id: 'c', text: 'Zero' }, { id: 'd', text: 'Only static' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Unlimited instances per class.' },
  { question: 'Interview: Where instance vars declared?', instruction: 'Interview: Where are instance vars declared?', options: [{ id: 'a', text: 'Inside methods' }, { id: 'b', text: 'Inside class, outside methods' }, { id: 'c', text: 'Only main' }, { id: 'd', text: 'Interface' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Instance vars at class level.' },
  { question: 'Interview: Method signature includes?', instruction: 'Interview: What is method signature?', options: [{ id: 'a', text: 'Name only' }, { id: 'b', text: 'Name + param types' }, { id: 'c', text: 'Body' }, { id: 'd', text: 'Return type only' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Signature = name + params (not return).' },
  { question: 'Interview: Objects on heap or stack?', instruction: 'Interview: Where are objects stored?', options: [{ id: 'a', text: 'Stack only' }, { id: 'b', text: 'Heap (ref may be stack)' }, { id: 'c', text: 'Neither' }, { id: 'd', text: 'Static only' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Objects on heap; refs on stack.' },
  { question: 'Interview: What is instantiation?', instruction: 'Interview: What is instantiation?', options: [{ id: 'a', text: 'Writing class' }, { id: 'b', text: 'Creating object from class' }, { id: 'c', text: 'Deleting object' }, { id: 'd', text: 'Inheritance' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Instantiation = creating instance.' },
  { question: 'Interview: Constructor private?', instruction: 'Interview: Can constructor be private?', options: [{ id: 'a', text: 'No' }, { id: 'b', text: 'Yes (singleton/factory)' }, { id: 'c', text: 'Only abstract' }, { id: 'd', text: 'Only static' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Private constructor for singleton.' },
  { question: 'Interview: Field vs local?', instruction: 'Interview: Instance field vs local?', options: [{ id: 'a', text: 'Same' }, { id: 'b', text: 'Field=object state; local=method' }, { id: 'c', text: 'Local only main' }, { id: 'd', text: 'Field only static' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Field=class level; local=method scope.' },
  { question: 'Interview: Encapsulation in class?', instruction: 'Interview: Encapsulation means?', options: [{ id: 'a', text: 'Many classes' }, { id: 'b', text: 'Bundle data+methods; control access' }, { id: 'c', text: 'Only methods' }, { id: 'd', text: 'Only public' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Encapsulation = data + methods + access control.' },
  { question: 'Interview: Why getters/setters?', instruction: 'Interview: Why getters/setters?', options: [{ id: 'a', text: 'Faster' }, { id: 'b', text: 'Validation, control, change impl' }, { id: 'c', text: 'Required' }, { id: 'd', text: 'Only static' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Control access; validate; change internals.' },
  { question: 'Interview: Single responsibility?', instruction: 'Interview: Single responsibility?', options: [{ id: 'a', text: 'One method' }, { id: 'b', text: 'One reason to change; one job' }, { id: 'c', text: 'One field' }, { id: 'd', text: 'One object' }], correctAnswer: 'b', correctOptionId: 'b', explanation: 'Class = one well-defined purpose.' },
];
const classesData = buildFromPairs(classesPairs);

// Shorthand for interview pairs (question, instruction, array of option texts, correct letter, explanation)
function pair(q, inst, opts, ans, exp) {
  const options = opts.map((t, i) => ({ id: String.fromCharCode(97 + i), text: t }));
  return { question: q, instruction: inst || q, options, correctAnswer: ans, correctOptionId: ans, explanation: exp };
}
const inheritancePairs = [
  pair('Interview: How to inherit in Java?', null, ['implements', 'extends', ':', 'inherits'], 'b', 'extends for class'),
  pair('Interview: Can class extend multiple classes?', null, ['Yes', 'No'], 'b', 'Single inheritance'),
  pair('Interview: Private members inherited?', null, ['Yes', 'No; not accessible'], 'b', 'Private not visible'),
  pair('Interview: super() purpose?', null, ['Create super', 'Call parent constructor', 'Override'], 'b', 'Invoke parent constructor'),
  pair('Interview: @Override purpose?', null, ['Required', 'Marks overriding; compiler check'], 'b', 'Compiler checks override'),
  pair('Interview: Object is superclass of?', null, ['None', 'All classes'], 'b', 'All extend Object'),
  pair('Interview: Constructor inherited?', null, ['Yes', 'No; parent invoked via super()'], 'b', 'Not inherited'),
  pair('Interview: super vs this?', null, ['Same', 'super=parent; this=current'], 'b', 'super=parent; this=current'),
  pair('Interview: When use inheritance?', null, ['Always', '"is-a" relationship'], 'b', 'Use for is-a'),
  pair('Interview: Method overriding?', null, ['Same name', 'Subclass replaces parent method'], 'b', 'Subclass implementation'),
  pair('Interview: Can override static?', null, ['Yes', 'No; hiding not overriding'], 'b', 'Static hidden not overridden'),
  pair('Interview: final class?', null, ['Cannot extend', 'Can extend'], 'a', 'final cannot extend'),
  pair('Interview: final method?', null, ['Cannot override', 'Can override'], 'a', 'final cannot override'),
  pair('Interview: Implicit super()?', null, ['Never', 'First line if no super'], 'b', 'Compiler inserts'),
  pair('Interview: super.method()?', null, ['Call parent version', 'Call current'], 'a', 'Calls parent'),
  pair('Interview: Hierarchical inheritance?', null, ['One child', 'Multiple extend same parent'], 'b', 'Multiple subclasses'),
  pair('Interview: Multilevel?', null, ['A→B→C', 'Only two levels'], 'a', 'Chain'),
  pair('Interview: Why no multiple inheritance?', null, ['No reason', 'Diamond problem'], 'b', 'Avoid diamond'),
  pair('Interview: Object methods in all classes?', null, ['No', 'Yes (toString, equals)'], 'b', 'Inherit from Object'),
  pair('Interview: Subclass add fields?', null, ['No', 'Yes'], 'b', 'Can add fields'),
];
const inheritanceData = buildFromPairs(inheritancePairs);

const polyPairs = [
  pair('Interview: Overloading vs overriding?', null, ['Same', 'Overload=diff params; Override=subclass replace'], 'b', 'Overload=compile; Override=runtime'),
  pair('Interview: When method chosen in overriding?', null, ['Compile time', 'Runtime'], 'b', 'Runtime polymorphism'),
  pair('Interview: Reference vs object type?', null, ['Same', 'Reference=visible; Object=which runs'], 'b', 'Ref=visibility; object=impl'),
  pair('Interview: Animal a=new Dog(); a.bark()?', null, ['Runs', 'Compile error if bark not in Animal'], 'b', 'Ref type decides callable'),
  pair('Interview: Overloading resolved when?', null, ['Runtime', 'Compile time'], 'b', 'Overload=compile-time'),
  pair('Interview: Polymorphism benefit?', null, ['Faster', 'Generic code; extend without change'], 'b', 'Code to supertype'),
  pair('Interview: Covariant return?', null, ['No', 'Yes; override return subtype'], 'b', 'Allowed'),
  pair('Interview: Dynamic dispatch?', null, ['Compile-time', 'Runtime method selection'], 'b', 'JVM picks at runtime'),
  pair('Interview: Interface polymorphism?', null, ['No', 'Yes; interface ref to impl'], 'b', 'Interface ref'),
  pair('Interview: Same name different params?', null, ['Override', 'Overload'], 'b', 'Overload'),
  pair('Interview: Animal a=new Dog(); a.sound()?', null, ['Animal', 'Dog'], 'b', 'Object type'),
  pair('Interview: @Override required?', null, ['Yes', 'No; recommended'], 'b', 'Recommended'),
  pair('Interview: Overload by return only?', null, ['Yes', 'No'], 'b', 'Must differ params'),
  pair('Interview: Two polymorphism types?', null, ['One', 'Compile-time + runtime'], 'b', 'Overload + override'),
  pair('Interview: Downcast when?', null, ['Never', 'Need subclass member'], 'b', 'Cast to subclass'),
  pair('Interview: instanceOf use?', null, ['Syntax', 'Check before safe cast'], 'b', 'Type check'),
  pair('Interview: Abstract + polymorphism?', null, ['No', 'Yes'], 'b', 'Abstract ref to concrete'),
  pair('Interview: Varargs overload?', null, ['No', 'Yes'], 'b', 'Valid overload'),
  pair('Interview: Static override?', null, ['Yes', 'No; hiding'], 'b', 'Hidden not overridden'),
  pair('Interview: List list=new ArrayList()?', null, ['No poly', 'Yes'], 'b', 'Interface ref'),
];
const encPairs = [
  pair('Interview: Encapsulation?', null, ['Many classes', 'Bundle data+methods; restrict access'], 'b', 'Data hiding'),
  pair('Interview: Typical field modifier?', null, ['public', 'private'], 'b', 'private'),
  pair('Interview: Data hiding?', null, ['Delete', 'Private; access via methods'], 'b', 'Hide internals'),
  pair('Interview: Why getters/setters?', null, ['Faster', 'Validation; control'], 'b', 'Control'),
  pair('Interview: Public getter private setter?', null, ['Invalid', 'Valid read-only'], 'b', 'Read-only'),
  pair('Interview: Package-private?', null, ['Same as private', 'Same package'], 'b', 'Package visible'),
  pair('Interview: protected?', null, ['Package only', 'Package + subclass'], 'b', 'Package + sub'),
  pair('Interview: Break encapsulation?', null, ['Private', 'Public mutable; expose internals'], 'b', 'Expose mutable'),
  pair('Interview: Immutable class?', null, ['No encap', 'Private final; no setters'], 'b', 'No setters'),
  pair('Interview: JavaBeans?', null, ['Other', 'getX/setX'], 'b', 'getX setX'),
  pair('Interview: Validation in setter?', null, ['Never', 'Common'], 'b', 'Validate'),
  pair('Interview: Expose internal List?', null, ['Return it', 'Copy or unmodifiable'], 'b', 'Don\'t expose'),
  pair('Interview: Modifier order?', null, ['public<private', 'private<package<protected<public'], 'b', 'Restrictiveness'),
  pair('Interview: Read-only?', null, ['Only setter', 'Only getter'], 'b', 'Getter only'),
  pair('Interview: Encapsulation and testing?', null, ['Harder', 'Easier'], 'b', 'Control deps'),
  pair('Interview: final field?', null, ['Opposite', 'Set once'], 'b', 'Immutable'),
  pair('Interview: Package-private when?', null, ['Never', 'Internal package'], 'b', 'Internal'),
  pair('Interview: Getter return array?', null, ['Yes', 'Copy/unmodifiable'], 'b', 'Don\'t expose'),
  pair('Interview: Setter validation?', null, ['setAge(a){age=a}', 'setAge(a){if(a>=0)age=a}'], 'b', 'Validate'),
  pair('Interview: Encapsulation vs abstraction?', null, ['Same', 'Encap=access; abstract=detail'], 'b', 'Different'),
];
const absPairs = [
  pair('Interview: Abstract class new?', null, ['Yes', 'No'], 'b', 'Cannot instantiate'),
  pair('Interview: Interface methods default?', null, ['Concrete', 'Public abstract'], 'b', 'Abstract'),
  pair('Interview: Abstract vs interface?', null, ['Same', 'Abstract=code; interface=contract'], 'b', 'Abstract=reuse'),
  pair('Interview: Multiple interfaces?', null, ['No', 'Yes'], 'b', 'Many'),
  pair('Interview: Abstract method?', null, ['Has body', 'No body'], 'b', 'No body'),
  pair('Interview: Interface field?', null, ['Instance', 'public static final'], 'b', 'Constants'),
  pair('Interview: default in interface?', null, ['No', 'Yes Java 8'], 'b', 'Since 8'),
  pair('Interview: Abstract have constructor?', null, ['No', 'Yes'], 'b', 'For super()'),
  pair('Interview: Implement multiple?', null, ['No', 'Yes'], 'b', 'implements A,B'),
  pair('Interview: Abstract extend interface?', null, ['No', 'Can implement'], 'b', 'Can'),
  pair('Interview: 100% abstraction?', null, ['Abstract class', 'Interface'], 'b', 'Interface'),
  pair('Interview: Marker interface?', null, ['Many methods', 'No methods'], 'b', 'Empty'),
  pair('Interview: Abstract have concrete method?', null, ['No', 'Yes'], 'b', 'Mix'),
  pair('Interview: Interface extend interface?', null, ['No', 'Yes'], 'b', 'Yes'),
  pair('Interview: Why abstract class?', null, ['Faster', 'Share code'], 'b', 'Reuse'),
  pair('Interview: Functional interface?', null, ['Many', 'One abstract'], 'b', 'SAM'),
  pair('Interview: static in interface?', null, ['No', 'Yes Java 8'], 'b', 'Since 8'),
  pair('Interview: Abstract without abstract methods?', null, ['Invalid', 'Valid'], 'b', 'Prevent instantiate'),
  pair('Interview: Interface Segregation?', null, ['Big', 'Small interfaces'], 'b', 'Small'),
  pair('Interview: When interface?', null, ['Never', 'Contract'], 'b', 'Contract'),
];
const compPairs = [
  pair('Interview: Composition relationship?', null, ['is-a', 'has-a'], 'b', 'has-a'),
  pair('Interview: Composition in code?', null, ['extends', 'Field of type'], 'b', 'Field'),
  pair('Interview: Prefer composition?', null, ['Never', 'When has-a'], 'b', 'Flexibility'),
  pair('Interview: Aggregation vs composition?', null, ['Same', 'Strong vs weak'], 'b', 'Strong has-a'),
  pair('Interview: Car and Engine?', null, ['Inheritance', 'Composition'], 'b', 'has-a'),
  pair('Interview: Dog and Animal?', null, ['Composition', 'Inheritance'], 'b', 'is-a'),
  pair('Interview: Dependency injection?', null, ['Only Spring', 'Pass deps in'], 'b', 'Inject'),
  pair('Interview: Composition benefit?', null, ['Faster', 'Swap parts'], 'b', 'Flexible'),
  pair('Interview: Library and Book?', null, ['Composition', 'Aggregation'], 'b', 'Weak'),
  pair('Interview: Strong has-a?', null, ['Aggregation', 'Composition'], 'b', 'Composition'),
  pair('Interview: new inside class?', null, ['Always', 'Tight coupling'], 'b', 'Coupling'),
  pair('Interview: Composition and testing?', null, ['Harder', 'Inject mocks'], 'b', 'Testable'),
  pair('Interview: extends vs field?', null, ['Same', 'extends=is-a; field=has-a'], 'b', 'Different'),
  pair('Interview: Fragile base?', null, ['Composition', 'Inheritance'], 'b', 'Inheritance'),
  pair('Interview: Reuse without inheritance?', null, ['No', 'Composition'], 'b', 'Composition'),
  pair('Interview: Car has Engine lifetime?', null, ['Independent', 'Part of Car'], 'b', 'Part of'),
  pair('Interview: Strategy pattern?', null, ['Inheritance', 'Composition'], 'b', 'Inject'),
  pair('Interview: Decorator?', null, ['Inheritance', 'Composition wrap'], 'b', 'Wrap'),
  pair('Interview: Favor composition?', null, ['Never', 'When flexible'], 'b', 'GoF'),
  pair('Interview: Multiple has-a?', null, ['Invalid', 'Valid'], 'b', 'Many fields'),
];
const bigoPairs = [
  pair('Interview: Big O describes?', null, ['Best case', 'Growth with n'], 'b', 'Growth'),
  pair('Interview: Binary search?', null, ['O(n)', 'O(log n)'], 'b', 'log n'),
  pair('Interview: Single loop n?', null, ['O(1)', 'O(n)'], 'b', 'Linear'),
  pair('Interview: Nested loops n?', null, ['O(n)', 'O(n²)'], 'b', 'Quadratic'),
  pair('Interview: ArrayList get index?', null, ['O(n)', 'O(1)'], 'b', 'Constant'),
  pair('Interview: HashMap get?', null, ['O(n)', 'O(1) avg'], 'b', 'Constant avg'),
  pair('Interview: TreeMap get?', null, ['O(1)', 'O(log n)'], 'b', 'Tree'),
  pair('Interview: Drop constants?', null, ['No', 'Yes'], 'b', 'O(2n)=O(n)'),
  pair('Interview: Merge sort?', null, ['O(n²)', 'O(n log n)'], 'b', 'n log n'),
  pair('Interview: Linear search?', null, ['O(log n)', 'O(n)'], 'b', 'Scan'),
  pair('Interview: Worst case?', null, ['Ignore', 'Report'], 'b', 'Usually worst'),
  pair('Interview: O(1)?', null, ['One op', 'Constant'], 'b', 'Constant'),
  pair('Interview: Space complexity?', null, ['Time', 'Extra space'], 'b', 'Memory'),
  pair('Interview: Naive Fibonacci?', null, ['O(n)', 'O(2ⁿ)'], 'b', 'Exponential'),
  pair('Interview: Two loops n?', null, ['O(n²)', 'O(n)'], 'b', 'Sequential'),
  pair('Interview: Dominant term?', null, ['Smallest', 'Largest'], 'b', 'Largest'),
  pair('Interview: Binary search needs?', null, ['Any', 'Sorted'], 'b', 'Sorted'),
  pair('Interview: ArrayList contains?', null, ['O(1)', 'O(n)'], 'b', 'Linear'),
  pair('Interview: HashSet add?', null, ['O(n)', 'O(1) avg'], 'b', 'Constant'),
  pair('Interview: Why Big O interview?', null, ['Syntax', 'Scalability'], 'b', 'Compare algo'),
];
const serPairs = [
  pair('Interview: Serializable?', null, ['Many methods', 'Marker'], 'b', 'Marker'),
  pair('Interview: transient?', null, ['Serialize', 'Exclude'], 'b', 'Not serialized'),
  pair('Interview: serialVersionUID?', null, ['Optional', 'Version'], 'b', 'Compatibility'),
  pair('Interview: ObjectOutputStream?', null, ['Read', 'Write'], 'b', 'Write'),
  pair('Interview: ObjectInputStream?', null, ['Write', 'Read'], 'b', 'Read'),
  pair('Interview: Static serialized?', null, ['Yes', 'No'], 'b', 'No'),
  pair('Interview: Parent not Serializable?', null, ['No effect', 'Child needs parent'], 'b', 'Parent state'),
  pair('Interview: InvalidClassException?', null, ['Never', 'UID mismatch'], 'b', 'UID'),
  pair('Interview: Externalizable?', null, ['Same', 'Custom'], 'b', 'Custom'),
  pair('Interview: transient use?', null, ['All', 'Sensitive'], 'b', 'Password'),
  pair('Interview: Default serialization?', null, ['All', 'Non-transient instance'], 'b', 'Instance'),
  pair('Interview: readObject/writeObject?', null, ['No', 'Custom'], 'b', 'Custom'),
  pair('Interview: Serialization inheritance?', null, ['Only child', 'Parent too'], 'b', 'Parent state'),
  pair('Interview: JSON vs Java serial?', null, ['Same', 'JSON portable'], 'b', 'Portable'),
  pair('Interview: Declare UID?', null, ['Required', 'Stable'], 'b', 'Stable'),
  pair('Interview: Deserialization creates?', null, ['Ref', 'New object'], 'b', 'New'),
  pair('Interview: Constructor on deserialize?', null, ['Yes', 'No default'], 'b', 'No'),
  pair('Interview: Transient final?', null, ['Always', 'Careful'], 'b', 'Careful'),
  pair('Interview: Serialize singleton?', null, ['Same', 'Can break'], 'b', 'readResolve'),
  pair('Interview: New code serialization?', null, ['Always Java', 'Consider JSON'], 'b', 'Alternatives'),
];
const polyData = buildFromPairs(polyPairs);
const encData = buildFromPairs(encPairs);
const absData = buildFromPairs(absPairs);
const compData = buildFromPairs(compPairs);
const bigoData = buildFromPairs(bigoPairs);
const serData = buildFromPairs(serPairs);

export const interviewDataBySlug = {
  'how-java-is-compiled': { activities: compilationActivities, quizQuestions: compilationQuizzes },
  'basic-syntax': { activities: basicSyntaxActivities, quizQuestions: basicSyntaxQuizzes },
  'variables-and-data-types': { activities: variablesActivities, quizQuestions: variablesQuizzes },
  'garbage-collection': { activities: gcActivities, quizQuestions: gcQuizzes },
  'classes-and-objects': classesData,
  'inheritance': inheritanceData,
  'polymorphism': polyData,
  'encapsulation': encData,
  'abstraction': absData,
  'composition': compData,
  'big-o-notation': bigoData,
  'serialization': serData,
};

export function getActivitiesAndQuizzes(slug) {
  const data = interviewDataBySlug[slug];
  return data ? { activities: data.activities, quizQuestions: data.quizQuestions } : { activities: [], quizQuestions: [] };
}
